import {Theme, ThemeType} from './theme';

export interface ThemeSet {
  readonly dark: Record<ThemeType, Theme>;
  readonly light: Record<ThemeType, Theme>;
}

export function createThemeSet(seedName: string = 'main'): ThemeSet {
  return {
    dark: {
      0: {
        background: 'neutral.c800',
        border: 'main.c200',
        display: 'main.c500',
        error: 'error.c300',
        mode: 'dark',
        primary: 'neutral.c100',
        secondary: 'neutral.c300',
        success: 'success.c300',
        type: 0,
        warning: 'warning.c300',
      },
      1: {
        background: 'black',
        border: 'main.c200',
        display: 'main.c500',
        error: 'error.c400',
        mode: 'dark',
        primary: 'neutral.c100',
        secondary: 'neutral.c400',
        success: 'success.c400',
        type: 1,
        warning: 'warning.c400',
      },
      2: {
        background: 'main.c900',
        border: 'main.c200',
        display: 'main.c500',
        error: 'error.c400',
        mode: 'dark',
        primary: 'neutral.c100',
        secondary: 'neutral.c400',
        success: 'success.c400',
        type: 2,
        warning: 'warning.c400',
      },
      3: {
        background: 'main.c700',
        border: 'main.c200',
        display: 'main.c400',
        error: 'error.c200',
        mode: 'dark',
        primary: 'white',
        secondary: 'neutral.c200',
        success: 'success.c200',
        type: 3,
        warning: 'warning.c200',
      },
    },
    light: {
      0: {
        background: 'neutral.c100',
        border: 'main.c800',
        display: 'main.c500',
        error: 'error.c600',
        mode: 'light',
        primary: 'neutral.c900',
        secondary: 'neutral.c700',
        success: 'success.c600',
        type: 0,
        warning: 'warning.c600',
      },
      1: {
        background: 'white',
        border: 'main.c800',
        display: 'main.c500',
        error: 'error.c600',
        mode: 'light',
        primary: 'neutral.c900',
        secondary: 'neutral.c700',
        success: 'success.c600',
        type: 1,
        warning: 'warning.c600',
      },
      2: {
        background: 'main.c200',
        border: 'main.c800',
        display: 'main.c600',
        error: 'error.c700',
        mode: 'light',
        primary: 'neutral.c900',
        secondary: 'neutral.c700',
        success: 'success.c700',
        type: 2,
        warning: 'warning.c700',
      },
      3: {
        background: 'main.c300',
        border: 'main.c800',
        display: 'main.c600',
        error: 'error.c800',
        mode: 'light',
        primary: 'black',
        secondary: 'neutral.c800',
        success: 'success.c800',
        type: 3,
        warning: 'warning.c800',
      },
    },
  };
}
